Various improvements for the CLI
gamedig/rust-gamedig pull request #159
Opened 2023-11-22 04:30 UTC by Douile

There was a bunch of things I wanted to add to the CLI so I put them in one PR.

- Added DNS lookup support
- Added JSON output option (and output the original response struct by default)
- Added ExtraRequestSettings as CLI arguments
- Added TimeoutSettings as CLI argument

If there's any that need more work or we don't want I can remove/split into other PR.

2023-11-22 10:41 UTC, CosminPerRam commented
Got #158 ahead (:

2023-11-22 13:35 UTC, cainthebest requested changes

2023-11-22 13:57 UTC, Douile commented on crates/cli/src/main.rs
Thanks for taking the time to review!

That's definitely a lot clearer :sweat_smile:.

I would say `query_server` is not really needed as it just calls through to the library function, perhaps we should improve the doc comments on that function :eyes: (I wonder who added them with very basic docs :joy:). Although having it might be better for readability.

I think the `get_timeout_settings` might not be necessary if clap default_value attributes are used (I don't use clap all that much so I didn't think to try before).

I'll get to work on a refactor soon.

One other thing I would like your thoughts on: the JSON output technically the Original Response object could also be output as JSON. I wonder if it might be useful to have one flag to choose between CommonResponse and OriginalResponse, and another to choose between pretty output and JSON output.

2023-11-22 22:23 UTC, cainthebest commented on crates/cli/src/main.rs
Thanks for the feedback!

I get what you're saying about `query_server`. It's just a middleman for the library function, so yeah, I give credit to the generate docs button in my IDE for the very basic docs xD. Readability is key, though, so keeping it might still be a good call or even better improve it.

Ah, the `get_timeout_settings`, I wouldn't know about that of the top of my head probably best to refer to docs.

And about the JSON output thing, you're onto something. Having a flag to switch between `CommonResponse` and `OriginalResponse`, and another for pretty vs. JSON output sounds super useful, although there is something that I noticed was that do we need to put `json` behind a feature flag as we would want it to be always included.

2023-11-23 16:53 UTC, Douile commented
The CI failure is due to poorly written CI (by me), and should be fixed by #161. Other than that I think this is pretty much good to go.

<details><summary>The new <code>--help</code> output (with JSON feature enabled</summary>

```
A command line interface for gamedig

Usage: gamedig-cli [OPTIONS] --game <GAME> --ip <IP>

Options:
  -g, --game <GAME>
          Unique identifier of the game for which server information is being queried

  -i, --ip <IP>
          Hostname or IP address of the server

  -p, --port <PORT>
          Optional query port number for the server. If not provided the default port for the game is used

  -j, --json
          Flag indicating if the output should be in JSON format

  -o, --output-mode <OUTPUT_MODE>
          Which response variant to use when outputting
          
          [default: generic]

          Possible values:
          - generic:           A generalised response that maps common fields from all game types to the same name
          - protocol-specific: The raw result returned from the protocol query, formatted similarly to how the server returned it

  -h, --help
          Print help (see a summary with '-h')

  -V, --version
          Print version

Timeouts:
      --connect-timeout <CONNECT>
          Socket connect timeout (in seconds)
          
          [default: 4]

      --read-timeout <READ>
          Socket read timeout (in seconds)
          
          [default: 4]

      --write-timeout <WRITE>
          Socket write timeout (in seconds)
          
          [default: 4]

      --retries <RETRIES>
          Number of retries per request
          
          [default: 0]

Query options:
      --hostname <HOSTNAME>
          The server's hostname.
          
          Used by: - [minecraft::RequestSettings#structfield.hostname]

      --protocol-version <PROTOCOL_VERSION>
          The protocol version to use.
          
          Used by: - [minecraft::RequestSettings#structfield.protocol_version]

      --gather-players <GATHER_PLAYERS>
          Whether to gather player information
          
          Used by: - [valve::GatheringSettings#structfield.players]
          
          [possible values: true, false]

      --gather-rules <GATHER_RULES>
          Whether to gather rule information.
          
          Used by: - [valve::GatheringSettings#structfield.rules]
          
          [possible values: true, false]

      --check-app-id <CHECK_APP_ID>
          Whether to check if the App ID is valid.
          
          Used by: - [valve::GatheringSettings#structfield.check_app_id]
          
          [possible values: true, false]
```

</details>

2023-11-23 23:10 UTC, cainthebest approved these changes
LGTM!

2023-11-26 22:59 UTC, merged